name: Build and Deploy Monorepo (Frontend + Backend)

on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install and Build Frontend
        working-directory: client
        run: |
          npm ci
          npm run build

      - name: Clean Nginx Directory
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            sudo rm -rf /var/www/html/*
            sudo mkdir -p /var/www/html
            sudo chown -R $USER:$USER /var/www/html

      - name: Deploy Frontend to Nginx Directory
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          source: "client/dist/"
          target: "/var/www/html"
          strip_components: 2

  build-backend:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Backend Dependencies
        working-directory: server
        run: |
          npm ci
          npm run build || true

      - name: Clean Backend Directory
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            rm -rf ~/backend
            mkdir -p ~/backend

      - name: Deploy Backend to VPS
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          source: "server"
          target: "~/backend"

      - name: Start Backend Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            cd ~/backend/server
            npm install --omit=dev
            npm run build
            pm2 delete backend || true
            pm2 start dist/index.js --name backend
